name: Build fzf

on:
  - workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init -- fzf/fzf
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - run: pip install build[virtualenv] wheel
      - run: python build_wheel.py
        working-directory: ./fzf
      - run: python -m build -s
        working-directory: ./fzf

      - run: |
          pip install --no-index -f fzf/dist/ fzf-bin
          fzf --version

      - uses: actions/upload-artifact@v3
        with:
          path: fzf/dist
