name: Build micro

on:
  - workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git submodule init -- micro/micro && git submodule update -- micro/micro
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - run: pip install build[virtualenv] wheel
      - run: python build_wheel.py
        working-directory: ./micro
      - run: python -m build -s
        working-directory: ./micro

      - run: |
          pip install --no-index -f micro/dist/ micro-editor
          which micro

      - uses: actions/upload-artifact@v3
        with:
          path: micro/dist
